import type {Storefront} from '@shopify/hydrogen';
import type {CurrencyCode} from '@shopify/hydrogen/storefront-api-types';
import {
  PACK_COLLECTION_HANDLE,
  PACK_FALLBACK_LIST,
  PACK_FREE_HANDLE,
  PACK_SLOTS,
  slotForProduct,
  type PackSlot,
} from './packOffer';
import {isPreorderHandle} from './preorder';

/**
 * The products the pack is built from, loaded once for every place that sells
 * it — the pack page and the homepage section, which must never offer two
 * different lists. What belongs to the pack is decided in ./packOffer.ts.
 */

export type PackVariant = {
  id: string;
  title: string;
  availableForSale: boolean;
  price: {amount: string; currencyCode: CurrencyCode};
  selectedOptions: Array<{name: string; value: string}>;
};

export type PackPiece = {
  id: string;
  title: string;
  handle: string;
  productType?: string | null;
  featuredImage: {
    id?: string | null;
    url: string;
    altText?: string | null;
    width?: number | null;
    height?: number | null;
  } | null;
  variants: {nodes: PackVariant[]};
};

export type PackData = {
  slots: Record<PackSlot, PackPiece[]>;
  free: PackPiece | null;
};

/** Guards the handles interpolated into the query below. */
const HANDLE = /^[a-z0-9-]+$/;

/*
 * Written out here rather than generated by codegen: the product aliases come
 * from the fallback list, so the query follows the configuration instead of
 * repeating it.
 *
 * Deliberately not tagged `#graphql`. That marker is what codegen collects
 * documents by, and it extracts them from the source as static text — a
 * document assembled from a constant at runtime is not something it can read,
 * so it must not be offered one. The types for this query are the ones
 * declared above instead.
 */
const PACK_QUERY = `
  fragment PackPiece on Product {
    id
    title
    handle
    productType
    featuredImage {
      id
      url
      altText
      width
      height
    }
    variants(first: 20) {
      nodes {
        id
        title
        availableForSale
        price {
          amount
          currencyCode
        }
        selectedOptions {
          name
          value
        }
      }
    }
  }
  query PackProducts(
    $collection: String!
    $country: CountryCode
    $language: LanguageCode
  ) @inContext(country: $country, language: $language) {
    collection(handle: $collection) {
      products(first: 50) {
        nodes {
          ...PackPiece
        }
      }
    }
    ${PACK_FALLBACK_LIST.filter((handle) => HANDLE.test(handle))
      .map(
        (handle, index) => `f${index}: product(handle: "${handle}") {...PackPiece}`,
      )
      .join('\n    ')}
  }
`;

export async function loadPack(storefront: Storefront): Promise<PackData> {
  const data = (await storefront.query(PACK_QUERY, {
    variables: {collection: PACK_COLLECTION_HANDLE},
  })) as Record<string, unknown> & {
    collection?: {products: {nodes: PackPiece[]}} | null;
  };

  const fromCollection = data?.collection?.products?.nodes ?? [];

  const fallback = PACK_FALLBACK_LIST.map(
    (_, index) => data?.[`f${index}`] as PackPiece | null,
  ).filter((piece): piece is PackPiece => Boolean(piece));

  /*
   * The collection wins as soon as it holds enough to build a pack. Below
   * that it is treated as absent: a half-filled collection would quietly drop
   * a whole slot from the page.
   */
  const usingCollection = fromCollection.length >= PACK_SLOTS.length;
  const pieces = usingCollection ? fromCollection : fallback;

  if (!usingCollection && fromCollection.length) {
    console.warn(
      `Pack: the "${PACK_COLLECTION_HANDLE}" collection holds only ${fromCollection.length} product(s) — falling back to the handles in app/lib/packOffer.ts.`,
    );
  }

  // Filed by what each product is, with anything unbuyable left out: a piece
  // nobody can add is not a choice, and the pre-ordered one is refused by the
  // cart itself.
  const slots = Object.fromEntries(
    PACK_SLOTS.map((slot) => [slot, [] as PackPiece[]]),
  ) as Record<PackSlot, PackPiece[]>;

  for (const piece of pieces) {
    if (isPreorderHandle(piece.handle)) continue;
    if (!piece.variants.nodes.some((variant) => variant.availableForSale)) {
      continue;
    }

    const slot = slotForProduct(piece);
    if (slot) slots[slot].push(piece);
  }

  const missing = PACK_SLOTS.filter((slot) => !slots[slot].length);
  if (missing.length) {
    console.warn(
      `Pack: nothing available for ${missing.join(', ')} — check app/lib/packOffer.ts against Shopify Admin.`,
    );
  }

  // The piece that is given. Looked up by handle rather than picked from a
  // slot: the discount is written for one product, and showing any other one
  // as free would be a promise Shopify will not keep.
  const free =
    pieces.find((piece) => piece.handle === PACK_FREE_HANDLE) ??
    fallback.find((piece) => piece.handle === PACK_FREE_HANDLE) ??
    null;

  if (!free) {
    console.warn(
      `Pack: the offered tee ("${PACK_FREE_HANDLE}") was not found — check PACK_FREE_HANDLE in app/lib/packOffer.ts.`,
    );
  }

  return {slots, free};
}

/** Whether the pack can be sold at all: a piece in every slot, and the tee. */
export function isPackSellable(pack: PackData | null): pack is PackData {
  return Boolean(
    pack?.free && PACK_SLOTS.every((slot) => pack.slots[slot]?.length),
  );
}
