import {useState} from 'react';
import {Link, useLoaderData} from 'react-router';
import {Image, Money} from '@shopify/hydrogen';
import type {Route} from './+types/pack';
import {AddToCartButton} from '~/components/AddToCartButton';
import {Reveal} from '~/components/Reveal';
import {useAside} from '~/components/Aside';
import {
  PACK_ADDS_FREE_LINE,
  PACK_COLLECTION_HANDLE,
  PACK_DISCOUNT_CODE,
  PACK_FALLBACK_LIST,
  PACK_FREE_HANDLE,
  PACK_SLOTS,
  slotForProduct,
  type PackSlot,
} from '~/lib/packOffer';
import {isPreorderHandle} from '~/lib/preorder';
import type {TranslationKey} from '~/lib/i18n';
import {useI18n, useT} from '~/lib/i18n';

/**
 * The essential pack: choose a pair of jeans, a longsleeve and a tee, each in
 * your size, and Shopify adds a fourth tee for nothing.
 *
 * This page creates no product, invents no price and calculates no reduction.
 * It shows real products at their real prices, puts the chosen lines in the
 * basket, and leaves the free tee to the "Buy X get Y" rule in Shopify Admin
 * — the only thing that can actually take money off. What the pack contains
 * is decided in ~/lib/packOffer.ts.
 */

/** The pack's lifestyle shot. Replace with a photo of the three pieces worn together. */
const PACK_IMAGE = {
  src: '/images/histoire-cerisiers.webp',
  width: 675,
  height: 1200,
};

type PackVariant = {
  id: string;
  title: string;
  availableForSale: boolean;
  price: {amount: string; currencyCode: string};
  selectedOptions: Array<{name: string; value: string}>;
};

type PackPiece = {
  id: string;
  title: string;
  handle: string;
  productType?: string | null;
  featuredImage: {
    id?: string | null;
    url: string;
    altText?: string | null;
    width?: number | null;
    height?: number | null;
  } | null;
  variants: {nodes: PackVariant[]};
};

export const meta: Route.MetaFunction = () => {
  return [
    {title: 'reda studio | pack essentiel'},
    {
      name: 'description',
      content:
        'Jeans, longsleeve and tee in the sizes you choose — with a fourth tee on us.',
    },
  ];
};

/** Guards the handles interpolated into the query below. */
const HANDLE = /^[a-z0-9-]+$/;

/*
 * Written out here rather than generated by codegen: the product aliases come
 * from the fallback list, so the query follows the configuration instead of
 * repeating it.
 *
 * Deliberately not tagged `#graphql`. That marker is what codegen collects
 * documents by, and it extracts them from the source as static text — a
 * document assembled from a constant at runtime is not something it can read,
 * so it must not be offered one. The types for this query are the ones
 * declared above instead.
 */
const PACK_QUERY = `
  fragment PackPiece on Product {
    id
    title
    handle
    productType
    featuredImage {
      id
      url
      altText
      width
      height
    }
    variants(first: 20) {
      nodes {
        id
        title
        availableForSale
        price {
          amount
          currencyCode
        }
        selectedOptions {
          name
          value
        }
      }
    }
  }
  query PackProducts(
    $collection: String!
    $country: CountryCode
    $language: LanguageCode
  ) @inContext(country: $country, language: $language) {
    collection(handle: $collection) {
      products(first: 50) {
        nodes {
          ...PackPiece
        }
      }
    }
    ${PACK_FALLBACK_LIST.filter((handle) => HANDLE.test(handle))
      .map(
        (handle, index) => `f${index}: product(handle: "${handle}") {...PackPiece}`,
      )
      .join('\n    ')}
  }
`;

export async function loader({context}: Route.LoaderArgs) {
  const data = (await context.storefront.query(PACK_QUERY, {
    variables: {collection: PACK_COLLECTION_HANDLE},
  })) as Record<string, unknown> & {
    collection?: {products: {nodes: PackPiece[]}} | null;
  };

  const fromCollection = data?.collection?.products?.nodes ?? [];

  const fallback = PACK_FALLBACK_LIST.map(
    (_, index) => data?.[`f${index}`] as PackPiece | null,
  ).filter((piece): piece is PackPiece => Boolean(piece));

  /*
   * The collection wins as soon as it holds enough to build a pack. Below
   * that it is treated as absent: a half-filled collection would quietly drop
   * a whole slot from the page.
   */
  const usingCollection = fromCollection.length >= PACK_SLOTS.length;
  const pieces = usingCollection ? fromCollection : fallback;

  if (!usingCollection && fromCollection.length) {
    console.warn(
      `Pack page: the "${PACK_COLLECTION_HANDLE}" collection holds only ${fromCollection.length} product(s) — falling back to the handles in app/lib/packOffer.ts.`,
    );
  }

  // Filed by what each product is, with anything unbuyable left out: a piece
  // nobody can add is not a choice, and the pre-ordered one is refused by the
  // cart itself.
  const slots = Object.fromEntries(
    PACK_SLOTS.map((slot) => [slot, [] as PackPiece[]]),
  ) as Record<PackSlot, PackPiece[]>;

  for (const piece of pieces) {
    if (isPreorderHandle(piece.handle)) continue;
    if (!piece.variants.nodes.some((variant) => variant.availableForSale)) {
      continue;
    }

    const slot = slotForProduct(piece);
    if (slot) slots[slot].push(piece);
  }

  const missing = PACK_SLOTS.filter((slot) => !slots[slot].length);
  if (missing.length) {
    console.warn(
      `Pack page: nothing available for ${missing.join(', ')} — check app/lib/packOffer.ts against Shopify Admin.`,
    );
  }

  // The piece that is given. Looked up by handle rather than picked from a
  // slot: the discount is written for one product, and showing any other one
  // as free would be a promise Shopify will not keep.
  const free =
    pieces.find((piece) => piece.handle === PACK_FREE_HANDLE) ??
    fallback.find((piece) => piece.handle === PACK_FREE_HANDLE) ??
    null;

  if (!free) {
    console.warn(
      `Pack page: the offered tee ("${PACK_FREE_HANDLE}") was not found — check PACK_FREE_HANDLE in app/lib/packOffer.ts.`,
    );
  }

  return {slots, free};
}

/** The size on a variant, from the size option when there is one. */
function sizeLabel(variant: PackVariant): string {
  const option = variant.selectedOptions.find(({name}) =>
    /taille|size|pointure/i.test(name),
  );
  return option?.value ?? variant.title;
}

function firstAvailable(piece: PackPiece): PackVariant | undefined {
  return (
    piece.variants.nodes.find((variant) => variant.availableForSale) ??
    piece.variants.nodes[0]
  );
}

export default function PackPage() {
  const {slots, free} = useLoaderData<typeof loader>();
  const {locale} = useI18n();
  const {open: openAside} = useAside();
  const t = useT();

  // One product and one size per slot, starting on the first piece in stock —
  // the same thing a product page does when it opens.
  const [choice, setChoice] = useState<
    Record<string, {product: string; variant: string}>
  >(() =>
    Object.fromEntries(
      PACK_SLOTS.map((slot) => {
        const piece = slots[slot]?.[0];
        return [
          slot,
          {
            product: piece?.id ?? '',
            variant: piece ? (firstAvailable(piece)?.id ?? '') : '',
          },
        ];
      }),
    ),
  );

  // The offered tee has a size of its own: it is a piece the customer will
  // wear, not a line item that happens to cost nothing.
  const [freeSize, setFreeSize] = useState(() =>
    free ? (firstAvailable(free)?.id ?? '') : '',
  );
  const freeVariant = free?.variants.nodes.find((node) => node.id === freeSize);

  const selection = PACK_SLOTS.map((slot) => {
    const pieces = slots[slot] ?? [];
    const piece = pieces.find((node) => node.id === choice[slot]?.product);
    const variant = piece?.variants.nodes.find(
      (node) => node.id === choice[slot]?.variant,
    );
    return {slot, pieces, piece, variant};
  });

  const complete = selection.every(({variant}) => variant?.availableForSale);
  const currency = selection[0]?.variant?.price.currencyCode ?? 'EUR';
  const total = selection.reduce(
    (sum, {variant}) => sum + Number(variant?.price.amount ?? 0),
    0,
  );

  const money = (amount: number) =>
    new Intl.NumberFormat(locale === 'fr' ? 'fr-FR' : 'en-GB', {
      style: 'currency',
      currency,
    }).format(amount);

  const chosenLines = selection
    .filter(({variant}) => variant)
    .map(({variant}) => ({merchandiseId: variant!.id, quantity: 1}));

  /*
   * The offered tee goes into the basket with the others, at its normal
   * price: the code is what brings it to zero, and a code cannot discount a
   * line that is not there. See PACK_ADDS_FREE_LINE.
   */
  const lines =
    PACK_ADDS_FREE_LINE && freeVariant
      ? [...chosenLines, {merchandiseId: freeVariant.id, quantity: 1}]
      : chosenLines;

  return (
    <div className="pack">
      <Reveal as="section" className="pack__hero">
        <img
          className="pack__hero-image"
          src={PACK_IMAGE.src}
          alt={t('pack.imageAlt')}
          width={PACK_IMAGE.width}
          height={PACK_IMAGE.height}
          loading="eager"
          decoding="async"
        />
        <div className="pack__hero-text">
          <p className="pack__eyebrow">{t('pack.eyebrow')}</p>
          <h1 className="pack__title">{t('pack.title')}</h1>
          <p className="pack__intro">{t('pack.intro')}</p>
          {/* Dit en une ligne, sans faux prix barré ni pastille : la remise
              est réelle et c'est Shopify qui l'applique — l'annoncer plus
              fort ne la rendrait pas plus vraie. */}
          <p className="pack__free">{t('pack.free')}</p>
        </div>
      </Reveal>

      <Reveal as="section" className="pack__picker">
        <h2 className="pack__section-title">{t('pack.piecesTitle')}</h2>

        {/* L'offre montrée plutôt qu'expliquée : les trois pièces en grand,
            un « + » entre elles, le résultat dessous. */}
        <ul className="pack__pieces">
          {selection.map(({slot, pieces, piece, variant}) => (
            <li className="pack__piece" key={slot}>
              {piece?.featuredImage ? (
                <Link to={`/products/${piece.handle}`} className="pack__shot">
                  <Image
                    data={piece.featuredImage}
                    alt={piece.featuredImage.altText || piece.title}
                    sizes="(min-width: 48em) 30vw, 88vw"
                    loading="lazy"
                  />
                </Link>
              ) : (
                <span className="pack__shot" />
              )}

              <span className="pack__slot">
                {t(`pack.slot.${slot}` as TranslationKey)}
              </span>

              <select
                className="pack__select"
                aria-label={t(`pack.slot.${slot}` as TranslationKey)}
                value={choice[slot]?.product ?? ''}
                onChange={(event) => {
                  const next = pieces.find(
                    (node) => node.id === event.target.value,
                  );
                  setChoice((current) => ({
                    ...current,
                    [slot]: {
                      product: event.target.value,
                      // A size only means something on the piece it belongs
                      // to: changing the piece starts its sizes over.
                      variant: next ? (firstAvailable(next)?.id ?? '') : '',
                    },
                  }));
                }}
              >
                {pieces.map((node) => (
                  <option key={node.id} value={node.id}>
                    {node.title}
                  </option>
                ))}
              </select>

              <div className="pack__piece-foot">
                <p className="pack__piece-price">
                  {variant ? <Money data={variant.price} /> : null}
                </p>

                <label className="pack__size">
                  <span className="pack__size-label">{t('pack.size')}</span>
                  <select
                    value={choice[slot]?.variant ?? ''}
                    onChange={(event) =>
                      setChoice((current) => ({
                        ...current,
                        [slot]: {
                          product: current[slot]?.product ?? '',
                          variant: event.target.value,
                        },
                      }))
                    }
                  >
                    {(piece?.variants.nodes ?? []).map((node) => (
                      <option
                        key={node.id}
                        value={node.id}
                        disabled={!node.availableForSale}
                      >
                        {sizeLabel(node)}
                        {node.availableForSale
                          ? ''
                          : ` — ${t('product.soldOut')}`}
                      </option>
                    ))}
                  </select>
                </label>
              </div>
            </li>
          ))}
          {free && (
            <li className="pack__piece pack__piece--free" key="free">
              <span className="pack__shot">
                {free.featuredImage && (
                  <Image
                    data={free.featuredImage}
                    alt={free.featuredImage.altText || free.title}
                    sizes="(min-width: 48em) 22vw, 88vw"
                    loading="lazy"
                  />
                )}
                {/* Écrit sur la photo : c'est là qu'on regarde, et c'est la
                    seule chose à comprendre de cette pièce. */}
                <span className="pack__free-tag">{t('pack.freeTag')}</span>
              </span>

              <span className="pack__slot">{t('pack.freeSlot')}</span>
              <p className="pack__free-name">{free.title}</p>

              <div className="pack__piece-foot">
                <p className="pack__piece-price pack__piece-price--free">
                  {t('pack.freeTag')}
                </p>

                <label className="pack__size">
                  <span className="pack__size-label">{t('pack.size')}</span>
                  <select
                    value={freeSize}
                    onChange={(event) => setFreeSize(event.target.value)}
                  >
                    {free.variants.nodes.map((node) => (
                      <option
                        key={node.id}
                        value={node.id}
                        disabled={!node.availableForSale}
                      >
                        {sizeLabel(node)}
                        {node.availableForSale
                          ? ''
                          : ` — ${t('product.soldOut')}`}
                      </option>
                    ))}
                  </select>
                </label>
              </div>
            </li>
          )}
        </ul>

        <div className="pack__totals">
          <div className="pack__totals-row pack__totals-row--strong">
            <span>{t('pack.total')}</span>
            <span>{money(total)}</span>
          </div>
          <p className="pack__free-note">
            {t('pack.freeNote', {code: PACK_DISCOUNT_CODE})}
          </p>
        </div>

        {/* `pack` : la page passe par l'action panier du pack, qui attache le
            code du pack et pas celui du duo. */}
        <AddToCartButton
          pack
          lines={lines}
          disabled={!complete}
          onClick={() => openAside('cart')}
        >
          {complete ? t('pack.add') : t('pack.unavailable')}
        </AddToCartButton>

        <p className="pack__note">{t('pack.note')}</p>
      </Reveal>
    </div>
  );
}
